ALTER TABLE TQUIZ
ADD COLUMN USER_ID UUID NOT NULL,
ADD FOREIGN KEY (USER_ID) REFERENCES TUSER(ID);

CREATE TABLE IF NOT EXISTS TQUIZ_ATTEMPT (
    ID UUID PRIMARY KEY,
    QUIZ_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    SCORE DECIMAL NOT NULL,
    COMPLETION_DATE TIMESTAMP NOT NULL,
    TIME_SPENT BIGINT,
    FOREIGN KEY (QUIZ_ID) REFERENCES TQUIZ(ID),
    FOREIGN KEY (USER_ID) REFERENCES TUSER(ID)
);
