CREATE TABLE IF NOT EXISTS TQUIZ (
    ID UUID PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TQUESTION (
    ID UUID PRIMARY KEY,
    QUIZ_ID UUID,
    QUESTION_TYPE VARCHAR(32) NOT NULL,
    STATEMENT VARCHAR(512) NOT NULL,
    HINT VARCHAR(255),
    EXPLANATION VARCHAR(255),
    CORRECT_ANSWER VARCHAR(32) NOT NULL,
    OPTIONS VARCHAR(768) NOT NULL,
    FOREIGN KEY (QUIZ_ID) REFERENCES TQUIZ(ID)
);
